### ISSUE TITLE
"add-apt-repository ppa:morphis/anbox-support" Errors [OS: Debian]

### ISSUE THREAD

**Issue by gjhklfdsa** [anbox/anbox#1021]
Log:
```
root@USR:/home/usr# add-apt-repository ppa:morphis/anbox-support
 
 More info: https://launchpad.net/~morphis/+archive/ubuntu/anbox-support
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmp7ptpj10u/pubring.gpg' created
gpg: /tmp/tmp7ptpj10u/trustdb.gpg: trustdb created
gpg: key 
```
[removed for privacy]
```
: public key "Launchpad PPA for morphis" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'S.gpg-agent.extra'

root@USR:/home/usr# 
```

**OS**: [Debian Stretch](https://www.wikipedia.org/wiki/Debian_version_history#Debian_9_.28Stretch.29)

**Following Instructions**: https://docs.anbox.io/userguide/install_kernel_modules.html#install-dkms-package-from-ppa

**Comment by c0rv1n0** [comment]
Same here. Seems that PPA,s is not supported by Debian, so I tried this: http://www.webupd8.org/2014/10/how-to-add-launchpad-ppas-in-debian-via.html

Still not working

**Comment by alenguav** [comment]
I have the same error with Ubuntu 18.04

**Comment by zetneteork** [comment]
same issue on Debian for missing file **Release**

**Comment by slimshady045** [comment]
used the (all) version??

> same issue on Debian for missing file **Release**
> 
> Work around was to install directly package from http://ppa.launchpad.net/morphis/anbox-support/ubuntu/pool/main/a/anbox-modules/

**Comment by MyWifeAA12** [comment]
You can try installing the kernel modules manually from https://github.com/anbox/anbox-modules without the need of PPA's and could be done with other ditros. 

Worked for me using Deepin 15.10 and Manjaro

**Comment by telcotronics** [comment]
Hay alguna solución al repositorio???

**Comment by AditSoni** [comment]
Still having issues

'The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.'

**Comment by storm1er** [comment]
Still an issue, this should be reopen

**Comment by skarmiglione** [comment]
Reopen the bug, this repo is not working.

**Comment by anniemburu** [comment]
Yea am also having the same problem

**Comment by Divlo** [comment]
Should definitely reopen, having the same issue.

**Comment by KrischnaGabriel** [comment]
Same

**Comment by englianhu** [comment]
```diff
+:~$ sudo add-apt-repository ppa:morphis/anbox-support  
 More info: https://launchpad.net/~morphis/+archive/ubuntu/anbox-support
Press [ENTER] to continue or Ctrl-c to cancel adding it.

+:~$ sudo apt update
-Err:55 http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release                   
-  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Reading package lists... Done                                                                
-E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

+:~$ sudo apt install linux-headers-generic anbox-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
-E: Unable to locate package anbox-modules-dkms

+:~$ sudo modprobe ashmem_linux
-modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.15.7-051507-generic

+:~$ sudo modprobe binder_linux
-modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.7-051507-generic
```
and https://github.com/anbox/anbox/issues/1271#issuecomment-581251487 , there has not yet update the  latest version `Ubuntu 20.04 LTS Focal Fossa`.

---

Reference:

- [How to install Anbox on `Ubuntu 20.04 LTS Focal Fossa`](https://www.how2shout.com/linux/how-to-install-anbox-on-ubuntu-20-04-lts-focal-fossa)
- https://github.com/anbox/anbox/issues/1289#issue-523949803
- https://github.com/anbox/anbox/issues/1638#issuecomment-715684188
- https://github.com/anbox/anbox/issues/1271#issuecomment-581251487

**Comment by englianhu** [comment]
> Still having issues
> 
> 'The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.'

```diff
+:~$ sudo add-apt-repository ppa:morphis/anbox-support  
 More info: https://launchpad.net/~morphis/+archive/ubuntu/anbox-support
Press [ENTER] to continue or Ctrl-c to cancel adding it.

+:~$ sudo apt update
-Err:55 http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release                   
-  404  Not Found [IP: 2001:67c:1560:8008::19 80]
Reading package lists... Done                                                                
-E: The repository 'http://ppa.launchpad.net/morphis/anbox-support/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

+:~$ sudo apt install linux-headers-generic anbox-modules-dkms
Reading package lists... Done
Building dependency tree       
Reading state information... Done
-E: Unable to locate package anbox-modules-dkms

+:~$ sudo modprobe ashmem_linux
-modprobe: FATAL: Module ashmem_linux not found in directory /lib/modules/5.15.7-051507-generic

+:~$ sudo modprobe binder_linux
-modprobe: FATAL: Module binder_linux not found in directory /lib/modules/5.15.7-051507-generic
```
and https://github.com/anbox/anbox/issues/1271#issuecomment-581251487 , there has not yet update the  latest version `Ubuntu 20.04 LTS Focal Fossa`.

---

Reference:

- [How to install Anbox on `Ubuntu 20.04 LTS Focal Fossa`](https://www.how2shout.com/linux/how-to-install-anbox-on-ubuntu-20-04-lts-focal-fossa)
- https://github.com/anbox/anbox/issues/1289#issue-523949803
- https://github.com/anbox/anbox/issues/1638#issuecomment-715684188
- https://github.com/anbox/anbox/issues/1271#issuecomment-581251487
