### ISSUE TITLE
session-manager crashes 

### ISSUE THREAD

**Issue by sevu** [anbox/anbox#1218]
.1. Please check that no similar bug is already reported. 
Looks similar to #1217, but I didn't see the java exception.

 .2. – .5. Not using snap, but the Archlinux AUR method. Pretty sure it's not a packaging issue. Let me know where I can find the logs / debug settings if required or how to create a debug build.

 .6. Please paste the result of `anbox system-info` below:

```
version: local-bdfda8c
cpu:
arch:  x86
brand: Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz
features: 
- aes
- sse4_1
- sse4_2
- avx
- avx2
os:
name: Arch Linux
version: 
snap-based: false
kernel:
version: Linux version 5.2.9-arch1-1-ARCH (builduser@heftig-119803) (gcc version 9.1.0 (GCC)) #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019
binder: true
ashmem: true
graphics:
egl:
vendor: Mesa Project
version: 1.4
extensions:
- EGL_ANDROID_blob_cache
- EGL_ANDROID_native_fence_sync
- EGL_CHROMIUM_sync_control
- EGL_EXT_buffer_age
- EGL_EXT_create_context_robustness
- EGL_EXT_image_dma_buf_import
- EGL_EXT_image_dma_buf_import_modifiers
- EGL_IMG_context_priority
- EGL_KHR_config_attribs
- EGL_KHR_create_context
- EGL_KHR_create_context_no_error
- EGL_KHR_fence_sync
- EGL_KHR_get_all_proc_addresses
- EGL_KHR_gl_colorspace
- EGL_KHR_gl_renderbuffer_image
- EGL_KHR_gl_texture_2D_image
- EGL_KHR_gl_texture_3D_image
- EGL_KHR_gl_texture_cubemap_image
- EGL_KHR_image
- EGL_KHR_image_base
- EGL_KHR_image_pixmap
- EGL_KHR_no_config_context
- EGL_KHR_reusable_sync
- EGL_KHR_surfaceless_context
- EGL_EXT_pixel_format_float
- EGL_KHR_wait_sync
- EGL_MESA_configless_context
- EGL_MESA_drm_image
- EGL_MESA_image_dma_buf_export
- EGL_MESA_query_driver
- EGL_NOK_texture_from_pixmap
- EGL_WL_bind_wayland_display
gles2:
vendor: Intel Open Source Technology Center
vendor: OpenGL ES 3.1 Mesa 19.1.5
extensions:
- GL_EXT_blend_minmax
- GL_EXT_multi_draw_arrays
- GL_EXT_texture_filter_anisotropic
- GL_EXT_texture_compression_s3tc
- GL_EXT_texture_compression_dxt1
- GL_EXT_texture_compression_rgtc
- GL_EXT_texture_format_BGRA8888
- GL_OES_compressed_ETC1_RGB8_texture
- GL_OES_depth24
- GL_OES_element_index_uint
- GL_OES_fbo_render_mipmap
- GL_OES_mapbuffer
- GL_OES_rgb8_rgba8
- GL_OES_standard_derivatives
- GL_OES_stencil8
- GL_OES_texture_3D
- GL_OES_texture_float
- GL_OES_texture_float_linear
- GL_OES_texture_half_float
- GL_OES_texture_half_float_linear
- GL_OES_texture_npot
- GL_OES_vertex_half_float
- GL_EXT_texture_sRGB_decode
- GL_OES_EGL_image
- GL_OES_depth_texture
- GL_OES_packed_depth_stencil
- GL_EXT_texture_type_2_10_10_10_REV
- GL_NV_conditional_render
- GL_OES_get_program_binary
- GL_APPLE_texture_max_level
- GL_EXT_discard_framebuffer
- GL_EXT_read_format_bgra
- GL_EXT_frag_depth
- GL_NV_fbo_color_attachments
- GL_OES_EGL_image_external
- GL_OES_EGL_sync
- GL_OES_vertex_array_object
- GL_OES_viewport_array
- GL_ANGLE_texture_compression_dxt3
- GL_ANGLE_texture_compression_dxt5
- GL_EXT_occlusion_query_boolean
- GL_EXT_robustness
- GL_EXT_texture_rg
- GL_EXT_unpack_subimage
- GL_NV_draw_buffers
- GL_NV_read_buffer
- GL_NV_read_depth
- GL_NV_read_depth_stencil
- GL_NV_read_stencil
- GL_EXT_draw_buffers
- GL_EXT_map_buffer_range
- GL_KHR_debug
- GL_KHR_robustness
- GL_OES_depth_texture_cube_map
- GL_OES_required_internalformat
- GL_OES_surfaceless_context
- GL_EXT_color_buffer_float
- GL_EXT_sRGB_write_control
- GL_EXT_separate_shader_objects
- GL_EXT_shader_implicit_conversions
- GL_EXT_shader_integer_mix
- GL_EXT_tessellation_point_size
- GL_EXT_tessellation_shader
- GL_INTEL_performance_query
- GL_EXT_base_instance
- GL_EXT_compressed_ETC1_RGB8_sub_texture
- GL_EXT_copy_image
- GL_EXT_draw_buffers_indexed
- GL_EXT_draw_elements_base_vertex
- GL_EXT_gpu_shader5
- GL_EXT_polygon_offset_clamp
- GL_EXT_primitive_bounding_box
- GL_EXT_render_snorm
- GL_EXT_shader_io_blocks
- GL_EXT_texture_border_clamp
- GL_EXT_texture_buffer
- GL_EXT_texture_cube_map_array
- GL_EXT_texture_norm16
- GL_EXT_texture_view
- GL_KHR_blend_equation_advanced
- GL_KHR_context_flush_control
- GL_KHR_robust_buffer_access_behavior
- GL_NV_image_formats
- GL_OES_copy_image
- GL_OES_draw_buffers_indexed
- GL_OES_draw_elements_base_vertex
- GL_OES_gpu_shader5
- GL_OES_primitive_bounding_box
- GL_OES_sample_shading
- GL_OES_sample_variables
- GL_OES_shader_io_blocks
- GL_OES_shader_multisample_interpolation
- GL_OES_tessellation_point_size
- GL_OES_tessellation_shader
- GL_OES_texture_border_clamp
- GL_OES_texture_buffer
- GL_OES_texture_cube_map_array
- GL_OES_texture_stencil8
- GL_OES_texture_storage_multisample_2d_array
- GL_OES_texture_view
- GL_EXT_blend_func_extended
- GL_EXT_buffer_storage
- GL_EXT_float_blend
- GL_EXT_geometry_point_size
- GL_EXT_geometry_shader
- GL_EXT_shader_samples_identical
- GL_KHR_no_error
- GL_OES_EGL_image_external_essl3
- GL_OES_geometry_point_size
- GL_OES_geometry_shader
- GL_OES_shader_image_atomic
- GL_EXT_clip_cull_distance
- GL_EXT_disjoint_timer_query
- GL_EXT_texture_compression_s3tc_srgb
- GL_MESA_shader_integer_functions
- GL_EXT_texture_compression_bptc
- GL_KHR_parallel_shader_compile
- GL_EXT_shader_framebuffer_fetch_non_coherent
- GL_EXT_texture_sRGB_R8
- GL_MESA_framebuffer_flip_y
- GL_EXT_depth_clamp
- GL_EXT_texture_query_lod
```

**Please describe your problem:**
Launching `anbox session-manager` crashes…

### Additional info:
`anbox container-manager` never crashes and keeps running.

In half of the cases `anbox session-manager` crashes with this message
```[ 2019-08-28 23:41:36] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2019-08-28 23:41:36] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2019-08-28 23:41:36] [daemon.cpp:61@Run] Container is not running
terminate called after throwing an instance of 'boost::wrapexcept<boost::log::v2_mt_posix::system_error>'
what():  Failed to set TLS value: Invalid argument
Stack trace (most recent call last) in thread 3672:
```
**Possibly an issue with boost 1.69?** I had it running some months ago.

===========================================
Other half of the cases are:
```
[ 2019-08-28 23:47:58] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2019-08-28 23:47:58] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2019-08-28 23:47:59] [daemon.cpp:61@Run] Container is not running
[ 2019-08-28 23:47:59] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
```

Sometimes I also manage to get a segfault in addition (relatively seldom though) Just repeatedly launch the command after failling again. Here's the backtrace;
```
Core was generated by `/usr/bin/anbox session-manager'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  x86_64_fallback_frame_state (context=0x7fad3dd50fb0, context=0x7fad3dd50fb0, fs=0x7fad3dd510a0) at ./md-unwind-support.h:63
63      ./md-unwind-support.h: No such file or directory.
[Current thread is 1 (Thread 0x7fad3dd52700 (LWP 4465))]
(gdb) backtrace
#0  x86_64_fallback_frame_state (context=0x7fad3dd50fb0, context=0x7fad3dd50fb0, fs=0x7fad3dd510a0) at ./md-unwind-support.h:63
#1  uw_frame_state_for (context=0x7fad3dd50fb0, fs=0x7fad3dd510a0) at /build/gcc/src/gcc/libgcc/unwind-dw2.c:1265
#2  0x00007fad5a836239 in _Unwind_Backtrace (
trace=0x556884075120 <backward::details::Unwinder<backward::StackTraceImpl<backward::system_tag::linux_tag>::callback>::backtrace_trampoline(_Unwind_Context*, void*)>, trace_argument=0x7fad3dd51270) at /build/gcc/src/gcc/libgcc/unwind.inc:302
#3  0x0000556884075a64 in backward::StackTraceImpl<backward::system_tag::linux_tag>::load_here(unsigned long) ()
#4  0x00005568840796d2 in backward::SignalHandling::handleSignal(int, siginfo_t*, void*) ()
#5  0x0000556884079d99 in backward::SignalHandling::sig_handler(int, siginfo_t*, void*) ()
#6  <signal handler called>
#7  0x0000556800000000 in ?? ()
#8  0x000055688408d9df in void anbox::Logger::Errorf<char const*>(boost::optional<anbox::Logger::Location> const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, char const*&&) ()
#9  0x000055688406505e in ?? ()
#10 0x00007fad5a90dcd4 in std::execute_native_thread_routine (__p=0x55688561d640) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/thread.cc:80
#11 0x00007fad5aaf257f in start_thread () from /usr/lib/libpthread.so.0
#12 0x00007fad5a75e0e3 in clone () from /usr/lib/libc.so.6
```

EDIT: using current master version

**Comment by D1mon** [comment]
same problem:
```
ANBOX_LOG_LEVEL=debug anbox session-manager
[ 2019-09-09 09:31:19] [Renderer.cpp:168@initialize] Using a surfaceless EGL context
[ 2019-09-09 09:31:19] [Renderer.cpp:251@initialize] Successfully initialized EGL
[ 2019-09-09 09:31:19] [service.cpp:41@Service] Successfully acquired DBus service name
[ 2019-09-09 09:31:19] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[ 2019-09-09 09:31:19] [session_manager.cpp:148@operator()] Lost connection to container manager, terminating.
[ 2019-09-09 09:31:20] [daemon.cpp:61@Run] Container is not running
terminate called after throwing an instance of 'boost::wrapexcept<boost::log::v2_mt_posix::system_error>'
  what():  Failed to set TLS value: Invalid argument
Stack trace (most recent call last) in thread 10386:
```

**Comment by sevu** [comment]
Recompiled and successfully launched anbox today. I don't see a specific commit for that, maybe it was fixed by the boost fixes.
