### ISSUE TITLE
segfault in anbox

### ISSUE THREAD

**Issue by supaplextor** [anbox/anbox#280]
[EE 2017-05-19 23:42:45] [client.cpp:49@start] Failed to start container: Failed to start container: Failed to start container
[WW 2017-05-19 23:42:45] [session_manager.cpp:140@operator()] Lost connection to container manager, terminating.
[EE 2017-05-19 23:42:45] [daemon.cpp:58@Run] Container is not running

Thread 20 "anbox" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffd0ff9700 (LWP 16698)]
0x00000000004f3e21 in anbox::container::Client::on_read_size(boost::system::error_code const&, unsigned long) ()
(gdb) where
#0  0x00000000004f3e21 in anbox::container::Client::on_read_size(boost::system::error_code const&, unsigned long) ()
#1  0x000000000055408e in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, std::function<void (boost::system::error_code const&, unsigned long)> >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#2  0x00000000004e9a65 in (anonymous namespace)::exception_safe_run(boost::asio::io_service&) ()
#3  0x00007ffff5c9ac80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff74446ba in start_thread (arg=0x7fffd0ff9700) at pthread_create.c:333
#5  0x00007ffff570982d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 

supaplex@hydrogen:~/anbox-work/anbox$ anbox system-info
version: 0.1.0
os:
  name: Ubuntu
  version: 16.04.2 LTS (Xenial Xerus)
  snap-based: false
kernel:
  version: Linux version 4.8.0-36-generic (buildd@lgw01-18) (gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) ) #36~16.04.1-Ubuntu SMP Sun Feb 5 09:39:57 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)
    extensions:
      - EGL_KHR_create_context
      - EGL_KHR_get_all_proc_addresses
      - EGL_KHR_gl_colorspace
      - EGL_KHR_reusable_sync
      - EGL_KHR_surfaceless_context
      - EGL_MESA_configless_context
  gles2:
    vendor: VMware, Inc.
    vendor: OpenGL ES-CM 1.1 Mesa 12.0.6
    extensions:
      - GL_EXT_blend_minmax
      - GL_EXT_multi_draw_arrays
      - GL_EXT_texture_lod_bias
      - GL_OES_byte_coordinates
      - GL_OES_fixed_point
      - GL_OES_stencil_wrap
      - GL_OES_compressed_paletted_texture
      - GL_OES_query_matrix
      - GL_OES_read_format
      - GL_OES_single_precision
      - GL_EXT_texture_compression_dxt1
      - GL_OES_draw_texture
      - GL_OES_point_size_array
      - GL_OES_point_sprite
      - GL_EXT_texture_format_BGRA8888
      - GL_OES_compressed_ETC1_RGB8_texture
      - GL_OES_depth24
      - GL_OES_element_index_uint
      - GL_OES_fbo_render_mipmap
      - GL_OES_framebuffer_object
      - GL_OES_mapbuffer
      - GL_OES_rgb8_rgba8
      - GL_OES_stencil8
      - GL_OES_texture_env_crossbar
      - GL_OES_texture_mirrored_repeat
      - GL_OES_texture_npot
      - GL_OES_EGL_image
      - GL_OES_packed_depth_stencil
      - GL_OES_texture_cube_map
      - GL_APPLE_texture_max_level
      - GL_EXT_discard_framebuffer
      - GL_EXT_read_format_bgra
      - GL_OES_blend_equation_separate
      - GL_OES_blend_func_separate
      - GL_OES_blend_subtract
      - GL_OES_EGL_image_external
      - GL_OES_EGL_sync
      - GL_OES_vertex_array_object
      - GL_ANGLE_texture_compression_dxt3
      - GL_ANGLE_texture_compression_dxt5
      - GL_EXT_map_buffer_range
      - GL_KHR_debug
      - GL_OES_surfaceless_context
      - GL_EXT_polygon_offset_clamp

**Comment by supaplextor** [comment]
The last make install is stable now. Not fully sure why. There were broken output files in care of java needing more memory while building some portions of 7.1.1. I'll open a new issue if needed later. Thank you!
