### ISSUE TITLE
Crashes if trying to run Music app

### ISSUE THREAD

**Issue by hrvoojex** [anbox/anbox#68]
Make sure you are running the latest version of Anbox before reporting an issue.

Please also check that no similar bug is already reported. Have a look on the
list of open bugs at https://github.com/anbox/anbox/issues

**Anbox release (`anbox version`) and system info (`anbox system-info`):**
anbox 0.1.0

version: 0.1.0
os:
  name: Ubuntu Core
  version: 16
  snap-based: true
kernel:
  version: Linux version 4.8.0-46-generic (buildd@lcy01-16) (gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12) ) #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017
  binder: true
  ashmem: true
graphics:
  egl:
    vendor: Mesa Project
    version: 1.4 (DRI2)

**Description of the problem:**
When starting Music app, anbox is crashing every time

**Expected:**
To open Music app

**Additional info:**

**Comment by DrPugsley** [comment]
Just chiming in to say I'm having the same problem

**Comment by rajamalw** [comment]
The same issue in Ubuntu 17.04 with kernel 4.10

**Comment by freundTech** [comment]
Here is the log:
```04-14 07:23:18.469  1181  1181 E AndroidRuntime: FATAL EXCEPTION: main
04-14 07:23:18.469  1181  1181 E AndroidRuntime: Process: com.android.music, PID: 1181
04-14 07:23:18.469  1181  1181 E AndroidRuntime: java.lang.RuntimeException: Unable to create service com.android.music.MediaPlaybackService: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3201)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.app.ActivityThread.-wrap5(ActivityThread.java)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6119)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: Caused by: java.lang.SecurityException: MODE_WORLD_READABLE no longer supported
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.app.ContextImpl.checkMode(ContextImpl.java:2134)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:354)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.app.ContextImpl.getSharedPreferences(ContextImpl.java:349)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.content.ContextWrapper.getSharedPreferences(ContextWrapper.java:164)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at com.android.music.MediaPlaybackService.onCreate(MediaPlaybackService.java:338)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	at android.app.ActivityThread.handleCreateService(ActivityThread.java:3191)
04-14 07:23:18.469  1181  1181 E AndroidRuntime: 	... 8 more
```

Apparently  MODE_WORLD_READABLE was removed in Android 7.0. There is already a patch fixing this in the android source tree, but it was merged after the tag anbox is using and is therefor not included.

https://android.googlesource.com/platform/packages/apps/Music/+log/HEAD?s=6036ce6127022880a3d9c99bd15db4c968f3e6a3

https://android.googlesource.com/platform/packages/apps/Music/+/6036ce6127022880a3d9c99bd15db4c968f3e6a3

**Comment by morphis** [comment]
Thanks! An update to a newer Android version is indeed needed. If anyone is interested in providing proper PRs to help with this that would be awesome!
