### ISSUE TITLE
sudo add-apt-repository ppa:morphis/anbox-support ERROR

### ISSUE THREAD

**Issue by exru** [anbox/anbox#728]
exru@hp:/home$ sudo add-apt-repository ppa:morphis/anbox-support
 
 More info: https://launchpad.net/~morphis/+archive/ubuntu/anbox-support
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmptje3f4s7/pubring.gpg' created
gpg: /tmp/tmptje3f4s7/trustdb.gpg: trustdb created
gpg: key 21C6044A875B67B7: public key "Launchpad PPA for morphis" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 688, in addkey_func
    func(**kwargs)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 386, in add_key
    return apsk.add_ppa_signing_key()
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 273, in add_ppa_signing_key
    cleanup(tmp_keyring_dir)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 234, in cleanup
    shutil.rmtree(tmp_keyring_dir)
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] Нет такого файла или каталога: 'S.gpg-agent.browser'

**Comment by morphis** [comment]
@exru On which distribution are you trying this?

**Comment by exru** [comment]
Linux hp 4.16.0-0.bpo.1-amd64 #1 SMP Debian 4.16.5-1~bpo9+1 (2018-05-06) x86_64 GNU/Linux

**Comment by morphis** [comment]
@exru The PPA isn't supported on Debian.

The only thing you can try is 

`$ wget https://launchpad.net/~morphis/+archive/ubuntu/anbox-support/+files/anbox-modules-dkms_10.1~20180523.2.xenial.c36965f_all.deb ; dpkg -i anbox-modules-dkms*.deb`

**Comment by exru** [comment]
@morphis The PPA isn't supported on Debian. lol
Close the issuer!

**Comment by lophi22** [comment]
#
https://linuxconfig.org/how-to-install-anbox-and-run-android-apps-in-linux#h1-software-requirements-and-conventions-used
