### ISSUE TITLE
orbot VPN 

### ISSUE THREAD

**Issue by Mahdi321** [anbox/anbox#817]
orbot VPN is not effective. Also psiphon does not connect

**Comment by Mahdi321** [comment]
About orbot : Despite firefox added to its VPN list but firefox still uses direct connection
About Psiphon, it cannot connect in VPN mode (tunnel whole device option)

**Comment by BobbyWibowo** [comment]
Can confirm Orbot doesn't work with Firefox and WebView. The only browser that I managed to get working with Orbot is Orweb, which must be because it directly connected to Orbot and didn't care about the whole VPN setup.

I didn't manage to get any other browsers other than Firefox to run sanely in Anbox (tried Chrome, Opera and Yandex; all x86 version).

**Comment by mikma** [comment]
I have tried both wireguard and orbot vpn and both fail with "VpnJni  : Cannot allocate TUN: Bad file descriptor".

```
03-20 12:16:56.110   110   388 E VpnJni  : Cannot allocate TUN: Bad file descriptor
03-20 12:16:56.111  1605  1748 D OrbotVpnService: tun2Socks has stopped
03-20 12:16:56.111  1605  1748 D OrbotVpnService: java.lang.IllegalStateException: Cannot create interface
03-20 12:16:56.111  1605  1748 D OrbotVpnService: 	at android.os.Parcel.readException(Parcel.java:1692)
03-20 12:16:56.111  1605  1748 D OrbotVpnService: 	at android.os.Parcel.readException(Parcel.java:1637)
03-20 12:16:56.111  1605  1748 D OrbotVpnService: 	at android.net.IConnectivityManager$Stub$Proxy.establishVpn(IConnectivityManager.java:1941)
03-20 12:16:56.111  1605  1748 D OrbotVpnService: 	at android.net.VpnService$Builder.establish(VpnService.java:769)
03-20 12:16:56.111  1605  1748 D OrbotVpnService: 	at org.torproject.android.service.vpn.OrbotVpnManager$2.run(OrbotVpnManager.java:333)

```

**Comment by mikma** [comment]
The /dev/tun device was missing. After adding it I get some other errors in logcat when enabling wireguard.

I created a tun device in /data on the host since mknod didn't seem to work in anbox:
```
x86_64:/dev # ls -l /dev/tun                                                                                                                                          
lrwxrwxrwx 1 root root 9 2019-03-20 16:49 /dev/tun -> /data/tun
x86_64:/dev # ls -l /data/tun                                                                                                                                         
crw-rw---- 1 system vpn 10, 200 2019-03-20 12:04 /data/tun

```

VPN errors:
```
03-20 16:56:58.774  1133  1149 I WireGuard/GoBackend/wg0: Attaching to interface tun0
03-20 16:56:58.776   111   159 D ConnectivityService: NetworkAgentInfo [VPN () - 105] EVENT_NETWORK_INFO_CHANGED, going from CONNECTING to CONNECTED
03-20 16:56:58.776   111   159 D ConnectivityService: Adding iface tun0 to network 105
03-20 16:56:58.776    41    78 E Netd    : netlink response contains error (Invalid argument)
03-20 16:56:58.776    41    78 E Netd    : failed to add interface tun0 to VPN netId 105
03-20 16:56:58.777   111   159 E ConnectivityService: Exception adding interface: java.lang.IllegalStateException: command '77 network interface add 105 tun0' failed with '400 77 addInterfaceToNetwork() failed (Invalid argument)'
03-20 16:56:58.777    41    78 E Netd    : interface tun0 not assigned to any netId
03-20 16:56:58.777   111   159 E ConnectivityService: Exception in addRoute for non-gateway: java.lang.IllegalStateException: command '78 network route add 105 tun0 0.0.0.0/0' failed with '400 78 addRoute() failed (No such device)'
```

**Comment by sasha-ch** [comment]
+1 this issue.
